library(raster)
einstein <- raster("./data-raw/einstein/einstein.gif")
meanshift <- raster("./data-raw/einstein/meanshift.gif")
contrast <- raster("./data-raw/einstein/contrast.gif")
impulse <- raster("./data-raw/einstein/impulse.gif")
blur <- raster("./data-raw/einstein/blur.gif")
jpg <- raster("./data-raw/einstein/jpg.gif")
einsteins <- stack(einstein, meanshift, contrast, impulse, blur, jpg)
devtools::use_data(einsteins, overwrite = TRUE)
